FORMAT: 1A
HOST: http://localhost:8080/

# agenda

Agenda is a simple API allowing consumers to schedule meeting on-line


## users [/users]
Next 2 apis are irrelevant to key

### Register [POST]
+ Request 
var request = require('request');

request({
  method: 'POST',
  url: 'https://localhost:8080/users',
  headers: {
    'Content-Type': 'application/json'
  },
  body: "{  \"Name\": \"admin\",  \"Password\": \"123456\",  \"Email\": \"2496063488@qq.com\", \"Phone\":\"13709095674\"}"
}, function (error, response, body) {
  console.log('Status:', response.statusCode);
  console.log('Headers:', JSON.stringify(response.headers));
  console.log('Response:', body);
});

+ Response 201 (application/json)

        {
            "Name": "admin",
            "Password": "123456",
            "Email": "2496063488@qq.com",
            "Phone": "13709095674"
        }
        
+ Response 400 ("text/plain")

"Name conflict"

### List All Users [GET]
+ Request 
var request = require('request');

request('https://localhost:8080/users', function (error, response, body) {
  console.log('Status:', response.statusCode);
  console.log('Headers:', JSON.stringify(response.headers));
  console.log('Response:', body);
});

+ Response 200 (application/json)

    {
      "kity": {
       "Name": "kity",
       "Password": "123",
       "Email": "123",
       "Phone": "123"
      },
      "land": {
       "Name": "land",
       "Password": "123",
       "Email": "123",
       "Phone": "123"
      },
      "ricky": {
       "Name": "ricky",
       "Password": "123",
       "Email": "123",
       "Phone": "123"
      }
    }

## user [/user]
User login and logout

### Log in [POST /user/login]
+ Request
var request = require('request');

request({
  method: 'POST',
  url: 'https://localhost:8080/user/login',
  headers: {
    'Content-Type': 'application/json'
  },
  body: "{  \"Name\": \"admin\",  \"Password\": \"123456\"}"
}, function (error, response, body) {
  console.log('Status:', response.statusCode);
  console.log('Headers:', JSON.stringify(response.headers));
  console.log('Response:', body);
});

+ Response 201 (application/json)
{"key":"63259110-7bba-4354-8086-a36724c33e47"}

+ Response 400 ("text/plain")

"Wrong name or wrong password"


### Log out[DELETE /user/logout/keys/{key}]
+ Response 204
